<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Eng</name>
   <tag></tag>
   <elementGuidId>226ab6d0-15f5-4687-a917-4a07b38fac0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.style_triggerBtn__XmquB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/ul/li[7]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b62d9013-8dd1-4eb6-a07d-8cd4c94a0643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style_triggerBtn__XmquB</value>
      <webElementGuid>36961ef7-dba3-4d50-9db9-1d24481973ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eng</value>
      <webElementGuid>b8b601b0-5e29-4fb2-b061-18761e700a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;style_headerWrapper__ffo9A style_bgLight__poLOJ&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;style_navbarWrapper__cL__c&quot;]/div[@class=&quot;style_navbarActionWrapper__nO10b&quot;]/ul[@class=&quot;style_navbarMenuList__rF6Ee&quot;]/li[7]/div[@class=&quot;style_languageDropdown__x_WkK&quot;]/button[@class=&quot;style_triggerBtn__XmquB&quot;]</value>
      <webElementGuid>2870cca3-0eeb-47d8-90ec-855a428141f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/ul/li[7]/div/button</value>
      <webElementGuid>c7d24526-023d-4f18-b517-99226a021d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div/button</value>
      <webElementGuid>6aa990b9-061b-4a31-9298-2efe2255306a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Eng' or . = 'Eng')]</value>
      <webElementGuid>51fe1c08-ab44-4369-897d-093889206483</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
