<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_IndIndonesia</name>
   <tag></tag>
   <elementGuidId>103aeb58-f9ad-4188-ac6f-68c52b66d6e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.style_languageDropdown__x_WkK.style_showOptionActive__hmUWi > ul > li:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/ul/li[7]/div/ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>911bf3ed-507f-4c7c-a496-01aa8c48cd89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IndIndonesia</value>
      <webElementGuid>3c360839-96ba-4e9a-a2b6-dd0122417379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;style_headerWrapper__ffo9A style_bgLight__poLOJ&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;style_navbarWrapper__cL__c&quot;]/div[@class=&quot;style_navbarActionWrapper__nO10b&quot;]/ul[@class=&quot;style_navbarMenuList__rF6Ee&quot;]/li[7]/div[@class=&quot;style_languageDropdown__x_WkK style_showOptionActive__hmUWi&quot;]/ul[1]/li[2]</value>
      <webElementGuid>64da0e45-a30a-48ec-a73c-c64406fcb79a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/ul/li[7]/div/ul/li[2]</value>
      <webElementGuid>5cca8d7c-952c-44a8-83ec-d2ddbbad1edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div/ul/li[2]</value>
      <webElementGuid>7f45e988-2848-4f53-8110-db5bdb5cb82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'IndIndonesia' or . = 'IndIndonesia')]</value>
      <webElementGuid>a43d447c-8938-4b50-a709-8acb874aa1a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
