<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Training</name>
   <tag></tag>
   <elementGuidId>af6b46fe-68e4-4eb5-bc53-adadf6557b12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Training')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3fef1e0d-7250-42bc-9ca6-c560c35b6e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hidden items-center gap-2 text-sm font-semibold leading-6 text-gray-900 dark:text-white lg:flex</value>
      <webElementGuid>14a71793-9dde-4747-964d-d5c2707b512d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>679a5c37-10c6-4e30-9b3c-6e6c1401d90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>8bf951fc-0629-460a-a7a5-1cd5baac40fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://training.linuxfoundation.org/application-development/</value>
      <webElementGuid>a470e48f-db0f-4900-bf29-3c6370b844e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Training</value>
      <webElementGuid>383c2c62-3671-4669-b7b4-1742b4f7eb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;__variable_46ef16 __variable_031e64 font-sans&quot;]/body[@class=&quot;bg-white dark:bg-gray-900&quot;]/header[@class=&quot;sticky left-0 right-0 top-0 z-50 border-b border-gray-200 bg-white/90 backdrop-blur-sm dark:border-gray-700 dark:bg-gray-900/90&quot;]/nav[@class=&quot;mx-auto flex max-w-7xl items-center justify-between px-6 py-3 lg:px-8&quot;]/div[@class=&quot;hidden lg:flex lg:gap-x-12&quot;]/a[@class=&quot;hidden items-center gap-2 text-sm font-semibold leading-6 text-gray-900 dark:text-white lg:flex&quot;]</value>
      <webElementGuid>01d4644e-abff-45cd-ae39-2410e09e526e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Training')]</value>
      <webElementGuid>59eeed11-e911-445a-9a1d-a134849c58b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://training.linuxfoundation.org/application-development/')]</value>
      <webElementGuid>a3420632-f7c3-4e0d-ac10-b6ff7485bdc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>d6b0374e-c67d-480e-a053-4867c8548861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://training.linuxfoundation.org/application-development/' and (text() = 'Training' or . = 'Training')]</value>
      <webElementGuid>a8affef6-67c6-4f89-8080-7a70672f8e24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
