<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Overview</name>
   <tag></tag>
   <elementGuidId>57525a0e-983f-4fde-9ca6-4f0f4e7abb77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-popover-panel-:r0:']/div/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>29571855-165f-42d5-98e9-9b3882ae9bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-between gap-4 font-semibold text-gray-900 dark:text-white</value>
      <webElementGuid>cd9d7c02-afb8-42b2-bc7b-3025e1c393a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Overview</value>
      <webElementGuid>a0261c16-eb43-4d90-b195-d2dac078277c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-popover-panel-:r0:&quot;)/div[@class=&quot;grid gap-4 p-4&quot;]/div[1]/a[@class=&quot;flex flex-col gap-1 rounded-lg px-3 py-2 text-sm leading-6 text-gray-900 hover:bg-gray-50 dark:hover:bg-gray-900&quot;]/span[@class=&quot;flex items-center justify-between gap-4 font-semibold text-gray-900 dark:text-white&quot;]</value>
      <webElementGuid>d006778e-2e83-4081-81e0-75d33ec415b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-popover-panel-:r0:']/div/div/a/span</value>
      <webElementGuid>4809fbf5-8a30-475a-9d39-bb46ca52a24e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a/span</value>
      <webElementGuid>fe31abd3-9f36-441a-8c5c-08ff751ff68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Overview' or . = 'Overview')]</value>
      <webElementGuid>693125dc-e144-47b2-8199-5a9468817ff5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
