<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Search</name>
   <tag></tag>
   <elementGuidId>94ffdcc6-9f18-4181-ba00-e8c53fa6a479</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.sprite.svg-search-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='search-form']/fieldset/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>913af93d-3ece-4c7f-9130-4faadb24e1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sprite svg-search-icon</value>
      <webElementGuid>bc37a4f1-b759-43b8-adcc-a323275aef94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-jsl10n</name>
      <type>Main</type>
      <value>search-input-button</value>
      <webElementGuid>71a95ced-227b-40f0-a7d5-09352be9e4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>0ed9c71a-f93a-442f-be92-56b3eec3d6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-form&quot;)/fieldset[1]/button[@class=&quot;pure-button pure-button-primary-progressive&quot;]/i[@class=&quot;sprite svg-search-icon&quot;]</value>
      <webElementGuid>f102a754-c017-496f-a81a-84d6883d3721</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search-form']/fieldset/button/i</value>
      <webElementGuid>ea7c70e4-ee1d-4563-bb13-e6d33d8cc150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>c0f1d0d6-7e19-48bc-9570-f717b47339bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>ec77c7b0-bd3c-4653-b189-e41f660fc739</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
